baseurl = ""
relativeurls = true
languageCode = "en-us"
title = "IPFS Distributions"

# No tags/categories
taxonomies = {}

[params]
[params.targetMap]
386 = "32-bit"
amd64 = "64-bit"
arm = "ARM"
arm64 = "ARM-64"

[params.architectureMap]
darwin = "macOS Binary"
freebsd = "FreeBSD Binary"
linux = "Linux Binary"
windows = "Windows Binary"
